#!/bin/sh
# -*- python -*-
# This file is bilingual. The following shell code finds our preferred python.
# Following line is a shell no-op, and starts a multi-line Python comment.
# See https://stackoverflow.com/a/47886254
""":"
# prefer MY_PYTHON environment variable, python3, python
MY_PREFERRED_PYTHONS="python3 python"
for cmd in "${MY_PYTHON:-}" ${MY_PREFERRED_PYTHONS}; do
    if command -v "$cmd" >/dev/null; then
        export MY_PYTHON="$(command -v "$cmd")"
        exec "${MY_PYTHON}" "$0" "$@"
    fi
done
echo "==> Error: $0 could not find a python interpreter!" >&2
exit 1
":"""

import os
import re
import sys
import shutil
import shlex
import argparse
import subprocess


def remove_front_matter(file_path):
    with open(file_path, 'r') as file:
        content = file.read()
        content = re.sub(r'^---[\s\S]*?---\n', '', content)
        content = '# Zejia LIN (林泽佳)\n' + content
    with open(file_path, 'w') as file:
        file.write(content)


if __name__ == '__main__':
    filedir = os.path.dirname(os.path.abspath(__file__))
    index_path = os.path.join(filedir, 'content', 'en', '_index.md')
    readme_path = os.path.join(filedir, 'README.md')
    shutil.copy2(index_path, readme_path)
    remove_front_matter(readme_path)
    
